### ISSUE TITLE
WnCC *Seasons of code :P

### ISSUE THREAD

**Issue by martiansideofthemoon** [Sumith1896/wncc-soc#1]
*Seasons, not Summer :P

**Comment by sumith1896** [comment]
Thanks :P

**Comment by sumith1896** [comment]
How's your GSoC going? Sorry couldn't get to talk, am a bit busy :smile:

**Comment by martiansideofthemoon** [comment]
Pretty nice :smile: It will finish earlier than schedule

**Comment by sumith1896** [comment]
Great! Do get more work till the period ends :smile:, keep the flow!
